### ISSUE TITLE
关于弹幕文本上传Github以及分析

### ISSUE THREAD

**Issue by simon300000** [bilibili-dd-center/bilibili-vtuber-danmaku#1]
首先是能做数据分析
然后是我本地存不下那么多→_→
讨论：
![image](https://user-images.githubusercontent.com/12656264/57440915-76221600-727b-11e9-8c60-cc28721bef13.png)

**Comment by simon300000** [comment]
还是用`TIME19:23ONLINE27383`吧，更好处理
第一个数字0-23，第二个数字0-59

**Comment by simon300000** [comment]
@TomoeMami 好了，能用了，你看看？

**Comment by TomoeMami** [comment]
😂我不会js怎么帮你看……

**Comment by TomoeMami** [comment]
看起来蛮不错的。

**Comment by simon300000** [comment]
这个repo毕竟会上传一大堆东西
哦对，有弹幕风暴检测功能，似乎有个很直白的地方指示弹幕是不是弹幕风暴23333

**Comment by TomoeMami** [comment]
求相关数据段

**Comment by simon300000** [comment]
稍等
我截图给你

**Comment by simon300000** [comment]
https://github.com/simon300000/bilibili-Vtuber-danmaku/blob/6a3da8f6a30d9cfa9a4625fd47b00da32aac5c83/index.js#L23

<img width="926" alt="image" src="https://user-images.githubusercontent.com/12656264/57528962-46037180-7366-11e9-8030-f371cf9622b9.png">

https://github.com/simon300000/bilibili-live-ws#wsoncmd

你看这个数值，好像不是0就是弹幕风暴

**Comment by simon300000** [comment]
要感谢战斗吧歌姬，他们在我调试的时候送了好几个节奏风暴
我就猜出来这个规律了

**Comment by simon300000** [comment]
我往NGA发了一个帖子
https://bbs.nga.cn/read.php?tid=17199360
目前这个repo就放着吧→_→，暂时大概没什么需要操作的

**Comment by TomoeMami** [comment]
不自动生成每天的统计的话，可能有兴趣来看这个的人不会多。

**Comment by simon300000** [comment]
具体能怎么统计呢→_→
其实我现在更希望有人接过这个任务，或者有人把这个repo作为数据源(之一)

**Comment by TomoeMami** [comment]
不知道。我的意思是基本上不会有人一条条看过去的吧，得对这些数据进行一下处理才会有人愿意看罢。

**Comment by simon300000** [comment]
本来就不会有人一条条看吧，有就奇怪了233333333
所以这么处理呢？我提供了数据源，目前想看看有没有人愿意做

**Comment by TomoeMami** [comment]
https://github.com/yanyiwu/nodejieba

**Comment by simon300000** [comment]
Mark了
过段时间回来嘿嘿嘿

**Comment by simon300000** [comment]
关于这个数据分析
其实前几天vtbs.moe的稳定性很差，一天会挂十几次（几天挂了95次）
这次我很注意稳定性，两边都改了一些，现在一个晚上没有挂过

但是既然这里多出来了一个repo，数据分析每天一次也可能比较CPU intensive，那我觉得有一个好办法就是我在那边开一个端口，然后直接这个程序的数据分析完每天push到vtbs.moe就好，这样vtbs.moe挂了也能继续分析

目前来看现在这个程序似乎也挺稳定的
可能还能拿来当数据库用

**Comment by simon300000** [comment]
有人表示了想看发送者身份的功能
考虑到直播间弹幕是会显示发送者身份的，所以并不算什么第三方功能侵犯隐私
所以权衡利弊，我个人倾向记录发送者mid
你怎么看→_→？

**Comment by TomoeMami** [comment]
如果你说的是NGA的回帖的话，他的意思是要看同传哥。同传哥的账号是固定的，所以只提取那几个账号的发言就好吧。
而且我记得有的同传哥会在翻译之前加上特殊符号以区别普通弹幕，对于这些同传弹幕可以直接正则提取。

**Comment by simon300000** [comment]
对对对就是他
哎，现在好混乱啊→_→
要不我新发个帖问一问所有人？
“关于数据收集的隐私问题”什么的

**Comment by TomoeMami** [comment]
关心这些的一般观众应该不会多，与其论坛发帖问所有人，不如直接联系各字幕组，问问他们有没有利用直播时候弹幕的计划。
一般观众其实也没什么动力来翻直播弹幕吧。

**Comment by simon300000** [comment]
联系字幕组
有点怕怕的2333

**Comment by TomoeMami** [comment]
爬虫挂了吗？我还想看看傻葵今晚的弹幕记录调查一下弹幕节奏呢。
https://github.com/simon300000/bilibili-Vtuber-danmaku/tree/master/21302477 5月11日的txt更新于3小时前

**Comment by simon300000** [comment]
没挂，我没更新。。。

**Comment by simon300000** [comment]
大概11点的时候的确炸了
虽然之后重启了，但是人数统计不能看了233

**Comment by simon300000** [comment]
![Unknown-17](https://user-images.githubusercontent.com/12656264/57578067-fdf46400-74b7-11e9-95f8-3f52e619e65d.png)

**Comment by TomoeMami** [comment]
png保存下来居然背景是黑色，不该是透明吗

**Comment by simon300000** [comment]
惊了，那是你那边的问题吧？

**Comment by TomoeMami** [comment]
原来是SAI没有透明图层……

**Comment by simon300000** [comment]
<img width="1213" alt="image" src="https://user-images.githubusercontent.com/12656264/57578163-86273900-74b9-11e9-9d84-f9d034081564.png">
另外一个版本


我要去NGA秀一秀233

**Comment by fzxiao233** [comment]
> 真记录下来了 每个vtb做个词云什么的也是挺有意思的
![1](https://user-images.githubusercontent.com/42691214/57578419-9beb2d00-74be-11e9-83e8-0bfe41a42d7a.png)
我刚也用你的数据做了个

**Comment by simon300000** [comment]
嘿嘿嘿欢迎欢迎
@fzxiao233 我是用jieba https://github.com/yanyiwu/cppjieba https://github.com/yanyiwu/nodejieba
分的词，加了自己的词典，代码和字典都在在monster branch
然后用d3-cloud https://github.com/jasondavies/d3-cloud 做的图

加了词典可能效果会更好一点→_→

**Comment by fzxiao233** [comment]
> 嘿嘿嘿欢迎欢迎
> @fzxiao233 我是用jieba https://github.com/yanyiwu/cppjieba https://github.com/yanyiwu/nodejieba
> 分的词，加了自己的词典，代码和字典都在在monster branch
> 然后用d3-cloud https://github.com/jasondavies/d3-cloud 做的图
> 
> 加了词典可能效果会更好一点→_→

我也是jieba分的词，刚想去写个字典来着
我直接用[wordcloud](https://github.com/amueller/word_cloud)生成的
以后就直接拖你的数据了233

**Comment by simon300000** [comment]
> > 嘿嘿嘿欢迎欢迎
> > @fzxiao233 我是用jieba https://github.com/yanyiwu/cppjieba https://github.com/yanyiwu/nodejieba
> > 分的词，加了自己的词典，代码和字典都在在monster branch
> > 然后用d3-cloud https://github.com/jasondavies/d3-cloud 做的图
> > 加了词典可能效果会更好一点→_→
> 
> 我也是jieba分的词，刚想去写个字典来着
> 我直接用[wordcloud](https://github.com/amueller/word_cloud)生成的
> 以后就直接拖你的数据了233

行啊嘿嘿
不过我那个字典还没啥东西
（要不要开一个 repo 专门放字典，然后一有新词就集中pr到一起→_→

**Comment by fzxiao233** [comment]
> > > 嘿嘿嘿欢迎欢迎
> > > @fzxiao233 我是用jieba https://github.com/yanyiwu/cppjieba https://github.com/yanyiwu/nodejieba
> > > 分的词，加了自己的词典，代码和字典都在在monster branch
> > > 然后用d3-cloud https://github.com/jasondavies/d3-cloud 做的图
> > > 加了词典可能效果会更好一点→_→
> > 
> > 
> > 我也是jieba分的词，刚想去写个字典来着
> > 我直接用[wordcloud](https://github.com/amueller/word_cloud)生成的
> > 以后就直接拖你的数据了233
> 
> 行啊嘿嘿
> 不过我那个字典还没啥东西
> （要不要开一个 repo 专门放字典，然后一有新词就集中pr到一起→_→

那就麻烦你新开repo了233

**Comment by simon300000** [comment]
@fzxiao233 @TomoeMami 这么多vtb相关repo
要不要建一个organization？不知道叫什么好(`vtb-dd`

**Comment by fzxiao233** [comment]
> @fzxiao233 @TomoeMami 这么多vtb相关repo
> 要不要建一个organization？不知道叫什么好(`vtb-dd`

github-dd-center（划掉

**Comment by simon300000** [comment]
> > @fzxiao233 @TomoeMami 这么多vtb相关repo
> > 要不要建一个organization？不知道叫什么好(`vtb-dd`
> 
> github-dd-center（划掉

vtb-dd-center/vtbs-dd-center

hummmmmmm

**Comment by TomoeMami** [comment]
最好还是在名字里面注明bilibili吧，以免被误以为这里包含了其他直播平台的数据。

**Comment by simon300000** [comment]
bilibili-dd-center?

**Comment by TomoeMami** [comment]
其他直播平台日本那边早就有人统计了罢

**Comment by TomoeMami** [comment]
进去之后要干什么呢

**Comment by simon300000** [comment]
看着办呗

**Comment by simon300000** [comment]
我觉得我要加入记录mid功能
考虑到直播的发言者其实不属于隐私，大家都能看到
所以经过考虑，我觉得还是记录吧
当然主要是因为https://github.com/3Shain/BiliChat/issues/34 的需求

**Comment by TomoeMami** [comment]
可以不记录用户名而记录uid吧

**Comment by simon300000** [comment]
嗯，就是记录数字

simon3000
simon3000@163.com

**Comment by imlonghao** [comment]
我觉着把数据塞数据库可能会好点吧？
今天我把我之前写的 recorder 拓展了一下，塞了 vtbs.moe 的列表进去，同时跑了一百多个 ws ..
今晚看看会不会挂掉 （捂脸

**Comment by simon300000** [comment]
> 我觉着把数据塞数据库可能会好点吧？
> 今天我把我之前写的 recorder 拓展了一下，塞了 vtbs.moe 的列表进去，同时跑了一百多个 ws ..
> 今晚看看会不会挂掉 （捂脸

主要是我想着txt直接上传github，所以不塞数据库
不知道你具体是怎么写的，但是我这里100多个ws似乎是没问题的，高峰时期占用内存120M，低谷不知道
<img width="767" alt="image" src="https://user-images.githubusercontent.com/12656264/58009671-8eb6e980-7b21-11e9-9e9c-721e6c3a6ce8.png">
47小时前重启过，稳定性挺好
有时似乎是B站在凌晨会维护，看log，那时候好像会掉线

之后我准备写一个静态站放github pages，git submodule这个repo，然后定时更新弹幕以及jieba分析，然后就可以做一个小网站看直播间的弹幕词云，谁发弹幕最多什么的。
然后可以ifram进vtbs.moe

说实在的，我觉得我这个程序代码写的挺难看的，如果你的程序写出来可以开放一个数据库的api接口什么的，那我这个repo大概可以改一改了→_→

主要我还是不大清晰可以拿这些数据看什么，BiliChat好像有拿来找脚本的意思，我就最多做个词云。。。

**Comment by TomoeMami** [comment]
git-annex好像有这方面的功能 https://git-annex.branchable.com/walkthrough/

>  removing files
> When you're using git-annex you can git rm a file just like you usually would with git. Just like with git, this removes the file from your work tree, but it does not remove the file's content from the git repository. If you check the file back out, or revert the removal, you can get it back.
> 
> Git-annex adds the ability to remove the content of a file from your local repository to save space. This is called "dropping" the file.
> 
> You can always drop files safely. Git-annex checks that some other repository still has the file before removing it.
> 
> Once dropped, the file will still appear in your work tree as a broken symlink. You can use git annex get to as usual to get this file back to your local repository.

**Comment by simon300000** [comment]
看了看这个git-annex的连接，似乎不支持github？
我现在在想着用git-lfs呢

**Comment by imlonghao** [comment]
> 不知道你具体是怎么写的，但是我这里100多个ws似乎是没问题的，高峰时期占用内存120M，低谷不知道

我这用 Go 写的，机子内存足够不想去看内存占用...

> 如果你的程序写出来可以开放一个数据库的api接口什么的

可以做开放接口，但是我可能要看看我这的稳定性能不能用再做...

**Comment by simon300000** [comment]
> > 不知道你具体是怎么写的，但是我这里100多个ws似乎是没问题的，高峰时期占用内存120M，低谷不知道
> 
> 我这用 Go 写的，机子内存足够不想去看内存占用...
> 
> > 如果你的程序写出来可以开放一个数据库的api接口什么的
> 
> 可以做开放接口，但是我可能要看看我这的稳定性能不能用再做...

Go应该比Node好多了吧。。。
ws的稳定性的话应该不用担心，直接重连就好，太频繁似乎也不会被ban的

**Comment by wudifeixue** [comment]
统计这个很喜欢，不过我看目前统计的人数不是很多，打算同步  
https://github.com/simon300000/vtbs.moe/blob/master/api/vtbs.js 么？

**Comment by simon300000** [comment]
> 统计这个很喜欢，不过我看目前统计的人数不是很多，打算同步
> https://github.com/simon300000/vtbs.moe/blob/master/api/vtbs.js 么？

同步的应该就是那边，不过要考虑有些没开直播间呀

**Comment by wudifeixue** [comment]
> > 统计这个很喜欢，不过我看目前统计的人数不是很多，打算同步
> > https://github.com/simon300000/vtbs.moe/blob/master/api/vtbs.js 么？
> 
> 同步的应该就是那边，不过要考虑有些没开直播间呀

哦这个确实，对了我在b站私信过你不过你没回，你是怎么通过uid提取直播间id的呀？不会是一个个手动查的吧？

**Comment by simon300000** [comment]
> > > 统计这个很喜欢，不过我看目前统计的人数不是很多，打算同步
> > > https://github.com/simon300000/vtbs.moe/blob/master/api/vtbs.js 么？
> > 
> > 
> > 同步的应该就是那边，不过要考虑有些没开直播间呀
> 
> 哦这个确实，对了我在b站私信过你不过你没回，你是怎么通过uid提取直播间id的呀？不会是一个个手动查的吧？

啊 B站这个私信也没提醒我。。。
`https://api.live.bilibili.com/room/v1/Room/getRoomInfoOld?mid=${mid}`

**Comment by cqjjjzr** [comment]
嘛..我准备近期添加直接发送到数据库的功能……

但是根据你的代码，似乎将数据发送到后端，由后端丢到数据库是更好的选择？

**Comment by simon300000** [comment]
@cqjjjzr 哇，似乎是很厉害的东西，要不要加群663606562→_→？

**Comment by wudifeixue** [comment]
能直接弄个数据库出来就帮大忙了，我一直头疼这么不好用的数据怎么做个UI出来呢

**Comment by simon300000** [comment]
怎么那么多人说我数据不好用→_→！

**Comment by wudifeixue** [comment]
哈哈。。毕竟是txt，你要是直接储存成json就很好了

**Comment by simon300000** [comment]
@wudifeixue JSON的话，增量储存是不是比较难？因为有结构嘛
不过我可以写一个txt2json的小软件→_→

**Comment by simon300000** [comment]
好了，这是json转换器→_→
https://github.com/bilibili-dd-center/bilibili-vtuber-danmaku#json格式

**Comment by simon300000** [comment]
rua，请用api.vtb.wiki
https://github.com/bilibili-dd-center/go-vtuber-wiki-api
